-- Script generated by SimpleSpy - credits to exx#9394
while true do
   wait(.1)
local args = {
   [1] = workspace.Treasures.Treasure1 -- Make this Teasure2 up to Treasure5 to get everything.  Easy EXP & unlock most animals.
}

game:GetService("ReplicatedStorage").TreasureEvent:FireServer(unpack(args))
end