-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
local HalloweenBreakables = game.Workspace.GameObjects.Breakables
local Event = game:GetService("ReplicatedStorage").Packages.Knit.Services.BreakableService.RF.HitBreakable

while wait() do
for i,v in pairs(game.Workspace.GameObjects.Breakables:GetChildren()) do
if v.MeshId == "rbxassetid://104113575502246" then
game.Workspace[game.Players.LocalPlayer.Name].HumanoidRootPart.CFrame = v.CFrame
for count = 0,23,1 do
Event:InvokeServer(v.Name)
wait()
end
else
game.Workspace[game.Players.LocalPlayer.Name].HumanoidRootPart.CFrame = v.CFrame
for count = 0,49,1 do
Event:InvokeServer(v.Name)
wait()
end
end
end
end