_G.auto = true 

while _G.auto == true do
    -- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Green"
}

game:GetService("ReplicatedStorage").Events.BallDropped:FireServer(unpack(args))

-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Roll"
}

game:GetService("ReplicatedStorage").Events.ResetEvent:FireServer(unpack(args))


-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

game:GetService("ReplicatedStorage").Events.GainSP:FireServer()


-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BallPoints",
    [2] = "BallValue",
    [3] = "PlinkoUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BallPoints",
    [2] = "XPValue",
    [3] = "PlinkoUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BallPoints",
    [2] = "PointSynergy",
    [3] = "PlinkoUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BallPoints",
    [2] = "DespawnTime",
    [3] = "PlinkoUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BallPoints",
    [2] = "XPSynergy",
    [3] = "PlinkoUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BoxPoints",
    [2] = "GreenValue",
    [3] = "BoxUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BoxPoints",
    [2] = "BallValueII",
    [3] = "BoxUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BoxPoints",
    [2] = "XPValueII",
    [3] = "BoxUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "BoxPoints",
    [2] = "BPtoBoxSynergy",
    [3] = "BoxUpgrades",
    [4] = 1
}

game:GetService("ReplicatedStorage").Events.PurchaseUpgrade:FireServer(unpack(args))
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

game:GetService("ReplicatedStorage").Events.EarnRevolutions:FireServer()



wait()
end