
local ohNumber1 = 100000000000000000000

game:GetService("ReplicatedStorage").GiveSpinUse_Event:FireServer(ohNumber1)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

game:GetService("ReplicatedStorage").GiveTrohpy_Event:FireServer(ohNumber1)

for i = 1, 100 do
    local ohString1 = "MegaLoffyPet"
    local ohString2 = "Equip"

    game:GetService("ReplicatedStorage").EquipPet_Event:FireServer(ohString1, ohString2)
end

