getgenv().GibMoney = false;




local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3", true))()

local w = library:CreateWindow("Main") -- Creates the window

local e = w:CreateFolder("Autofarm")


-- Script generated by SimpleSpy - credits to exx#9394


e:Toggle("Autofarm enable",function(bool)
    getgenv().GibMoney = bool
    print("Auto Upgrade Bottles Is: ', Bool")
    if bool then
        domoney();

    end
end)

function domoney()
    spawn(function ()
        while GibMoney == true do

          for i, v in pairs(game:GetService("Workspace"):GetDescendants()) do
                      if v:FindFirstChild("ProximityPrompt") then
                          fireproximityprompt(v.ProximityPrompt)
              end
          end
          wait()
        end
    end)
end

e:Label("Woody - Scripter",{
    TextSize = 15; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
    BgColor = Color3.fromRGB(69,69,69); -- Self Explaining

})