-- Script generated by SimpleSpy - credits to exx#9394

local args = {
   [1] = "Equip",
   [2] = "Hat",
   [3] = "Rainbow",
   [4] = "GetALifeKid"
}

game:GetService("ReplicatedStorage").Action:FireServer(unpack(args))