 while true do
   
    -- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Plain Case"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlaceItem:FireServer(unpack(args))

wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "finish editing component"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Motherboard",
    [2] = game:GetService("Players").LocalPlayer.PcItems.P03
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "PowerSuply",
    [2] = game:GetService("Players").LocalPlayer.PcItems["Bronze 200w"]
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Cpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems["3 1200"]
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Ram",
    [2] = game:GetService("Players").LocalPlayer.PcItems["Ram 1Gb"]
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Memory",
    [2] = game:GetService("Players").LocalPlayer.PcItems["32Gb"]
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))

wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Gpu",
    [2] = game:GetService("Players").LocalPlayer.PcItems["Gpu 150"]
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.PlacePart:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "groupPart"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuildPc:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Enter Name"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.Save:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Enter Name"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.Sell:FireServer(unpack(args))



game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.Sell:FireServer(unpack(args))

wait(3)

-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Plain Case",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))

wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "P03",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Bronze 200w",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "3 1200",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Ram 1Gb",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "32Gb",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))
wait(1)
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

local args = {
    [1] = "Gpu 150",
    [2] = false,
    [3] = "1"
}

game:GetService("ReplicatedStorage").Resources.Remotes.RemoteEvents.BuyItem:FireServer(unpack(args))

wait(1)

end
   