getgenv().autofarm = true

while autofarm == true do



local args = {
  [1] = "Circle"
}

game:GetService("ReplicatedStorage").Remotes.Win:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
  [1] = 1
}

game:GetService("ReplicatedStorage").Remotes.Award:FireServer(unpack(args))
 

wait()
end