game:GetService("ReplicatedStorage"):WaitForChild("Badge1Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge5Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge10Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge1000Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge100Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge25Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge500Win"):FireServer()
game:GetService("ReplicatedStorage"):WaitForChild("Badge50Win"):FireServer()
