-- Script generated by TurtleSpy, made by Intrer#0421

local player = game.Players.LocalPlayer
local userInputService = game:GetService("UserInputService")

local function onKeyPress(input)
    if input.KeyCode == Enum.KeyCode.C then
        game:GetService("ReplicatedStorage").Remotes.Freeze:FireServer()
    end
end

userInputService.InputBegan:Connect(onKeyPress)
