-- Script generated by R2Sv2
-- R2Sv2 fixed by ButterflyEffect, dragging function Danisty§#9161
-- Remote Path: game:GetService("Workspace").Remote.ItemHandler
 
local A_1 = game:GetService("Workspace")["Prison_ITEMS"].single["Crude Knife"].ITEMPICKUP
local Event = game:GetService("Workspace").Remote.ItemHandler
Event:InvokeServer(A_1)
