-- Generated by Hydroxide's Upvalue Scanner

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()

local scriptPath = game:GetService("ReplicatedStorage").Assets.Modules.ToolHandler
local closureName = "Unnamed function"
local upvalueIndex = 1
local closureConstants = {
    [1] = "inputs",
    [2] = "settings",
    [3] = "firingEnabled",
    [4] = "firingFiremodeSwitchable",
    [5] = "mouseType",
    [6] = "keyType"
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = math.huge
local elementIndex = "magazine"


-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS
debug.getupvalue(closure, upvalueIndex)[elementIndex] = value