-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").username.Character,
    [2] = 30,
    [3] = 15,
    [4] = "Classic",
    [5] = 1.35
}

game:GetService("ReplicatedStorage").Game.Remotes.Slap:FireServer(unpack(args))