-- Script generated by SimpleSpy - credits to exx#9394
game.Players.LocalPlayer:GetMouse().KeyDown:Connect(function(key) if key == 'r' then
-- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Events.Attack:FireServer()

end
end
)