game:GetService'RunService'.RenderStepped:Connect(function()
task.spawn(function() -- prevent blocking frame render
for i=0,1000,1 do
   -- Script generated by SimpleSpy

local args = {
   [1] = game:GetService("Players").LocalPlayer,
   [2] = your word amount here
}

game:GetService("ReplicatedStorage").WordsDonation:FireServer(unpack(args))

end
end)
end)