game:GetService'RunService'.RenderStepped:Connect(function()
task.spawn(function() -- prevent blocking frame render
for i=0,1000,1 do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = "Wear",
        [2] = "11297746",
        [3] = "Hats"
    }
}

game:GetService("ReplicatedStorage").WearItem:FireServer(unpack(args))
end
end)
end)