-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
local ohString1 = "Join"
local ohString2 = "viktim" --victim name
game:GetService("ReplicatedStorage").RemoteEvents.General.CoalitionRequests:FireServer(ohString1, ohString2)