-- This script was generated by Hydroxide's RemoteSpy httpsgithub.comUpboltHydroxide

local ohTable1 = {
[1] = 2,
[2] = Coins,
[3] = 500,
[4] = Currency,
[5] = Coins,
[6] = 999999,
[7] = Coins Master,
[8] = Mine 500 Coins,
[9] = Color3.new(0.607843, 1, 0.0196078),
[10] = 3
}

gameGetService(ReplicatedStorage).Functions.ClaimQuestInvokeServer(ohTable1)