-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

local A_1 =
{
[1] = -99999999999999,
[2] = -99999999999999
}
local A_2 = "General"
local A_3 = "Loaded Armory"
local Event = game:GetService("ReplicatedStorage").UnlockNode
Event:FireServer(A_1, A_2, A_3)