-- Generated by Hydroxide's Upvalue Scanner: https://github.com/Upbolt/Hydroxide

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()

local scriptPath = game:GetService("Players").LocalPlayer.Backpack["Remington 870"].GunInterface
local closureName = "reloadGun"
local upvalueIndex = 8
local closureConstants = {
 [1] = "Play",
 [2] = "ReloadEvent",
 [3] = "FireServer",
 [4] = "ReloadSound",
 [5] = "Clone",
 [6] = "Parent"
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = 500
local elementIndex = "CurrentAmmo"


-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS
debug.getupvalue(closure, upvalueIndex)[elementIndex] = value

-- Generated by Hydroxide's Upvalue Scanner: https://github.com/Upbolt/Hydroxide

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()

local scriptPath = game:GetService("Players").LocalPlayer.Backpack["Remington 870"].GunInterface
local closureName = "reloadGun"
local upvalueIndex = 8
local closureConstants = {
 [1] = "Play",
 [2] = "ReloadEvent",
 [3] = "FireServer",
 [4] = "ReloadSound",
 [5] = "Clone",
 [6] = "Parent"
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = 500
local elementIndex = "MaxAmmo"


-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS
debug.getupvalue(closure, upvalueIndex)[elementIndex] = value