-- Script generated by SimpleSpy - credits to exx#9394

local args = {
   [1] = "ClickPower",
   [2] = 555555, -- change here
   [3] = 1
}

game:GetService("ReplicatedStorage").RemoteEvents.Rocket_RemoteEvent:FireServer(unpack(args))