-- Script generated by SimpleSpy - credits to exx#9394

local args = {
   [1] = "CheckAdd",
   [2] = 555555 --change here.
}

game:GetService("ReplicatedStorage").RemoteEvents.Star_RemoteEvent:FireServer(unpack(args))