local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/shlexware/Orion/main/source')))()
local Window = OrionLib:MakeWindow({Name = "Op Battleground", HidePremium = false, SaveConfig = true, ConfigFolder = "OrionTest"})

local Tab = Window:MakeTab({
 Name = "Idk lel",
 Icon = "rbxassetid://4483345998",
 PremiumOnly = false
})
local Section = Tab:AddSection({
 Name = "Main"

})
Tab:AddButton({
 Name = "Hollow Purple (One Shot)",
 Callback = function()
  local A_1 = "Hollow"
local Event = game:GetService("ReplicatedStorage").Remotes.Gojo
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Gear 5",
 Callback = function()
  local A_1 = "Awaken"
local Event = game:GetService("ReplicatedStorage").Remotes.Luffy2
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Imaginary Purple ( Deals 50 dmg)",
 Callback = function()
     local A_1 = "HollowPurple"
local Event = game:GetService("ReplicatedStorage").Remotes.Gojo
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Sukuna Domain Expansion (Not Op :[)",
 Callback = function()
     -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "TrueDomain"

game:GetService("ReplicatedStorage").Remotes.Yuji:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Pure Love",
 Callback = function()
      local A_1 = "PureLove"
local Event = game:GetService("ReplicatedStorage").Remotes.Yuta
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Black Flash (Yuta)",
 Callback = function()
     local A_1 = "BlackFlash"
local Event = game:GetService("ReplicatedStorage").Remotes.Yuta
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Kaminari",
 Callback = function()
     -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Kaminari"

game:GetService("ReplicatedStorage").Remotes.Luffy2:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Giant Stomp",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Giant"

game:GetService("ReplicatedStorage").Remotes.Luffy2:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Infinite Void",
 Callback = function()
    local ohString1 = "TrueDomain"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Red Normal",
 Callback = function()
   -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Red"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Normal Blue",
 Callback = function()
   -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Blue"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Martial Combo",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Barrage"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Infinity Counter",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Hora"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Maximum Red",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "MaxRed"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Maximum Blue",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "MaxBlue"

game:GetService("ReplicatedStorage").Remotes.Gojo:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Final Smash (OP)",
 Callback = function()
      local A_1 = "FinalSmash"
local Event = game:GetService("ReplicatedStorage").Remotes.Deku
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Rengoku Awaken (Scares People Off)",
 Callback = function()
     local A_1 = "Awaken"
local Event = game:GetService("ReplicatedStorage").Remotes.Rengoku
Event:FireServer(A_1)
   end    
})
local Section = Tab:AddSection({
 Name = "Emotes"
})
Tab:AddButton({
 Name = "Arusa Stance",
 Callback = function()
    local A_1 = "Asura Stance"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "There's Nothing We Can Do",
 Callback = function()
    local A_1 = "Ninja Wait"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Come Closer",
 Callback = function()
    local A_1 = "Come Closer"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Heart Wand",
 Callback = function()
    local A_1 = "Heart Wand"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Dunk!",
 Callback = function()
    local A_1 = "Dunk"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
Tab:AddButton({
 Name = "Dracoball Juggle",
 Callback = function()
      local A_1 = "Dracoball Juggle"
local Event = game:GetService("ReplicatedStorage").Remotes.Emotes.Emote
Event:FireServer(A_1)
   end    
})
local Tab = Window:MakeTab({
 Name = "Admin Stuff",
 Icon = "rbxassetid://4483345998",
 PremiumOnly = false
})

local Section = Tab:AddSection({
 Name = "Admins Thingy"

})
Tab:AddButton({
 Name = "Gon",
 Callback = function()
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Awaken"

game:GetService("ReplicatedStorage").Remotes.Gon:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Rock",
 Callback = function()
    local ohString1 = "Rock"

game:GetService("ReplicatedStorage").Remotes.Gon:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Paper",
 Callback = function()
    local ohString1 = "Paper"

game:GetService("ReplicatedStorage").Remotes.Gon:FireServer(ohString1)
   end    
})
Tab:AddButton({
 Name = "Scissor",
 Callback = function()
   local ohString1 = "Scissor"

game:GetService("ReplicatedStorage").Remotes.Gon:FireServer(ohString1)
   end    
})
local Tab = Window:MakeTab({
 Name = "Credits",
 Icon = "rbxassetid://4483345998",
 PremiumOnly = false
})
local Section = Tab:AddSection({
 Name = "Credits"

})
Tab:AddButton({
 Name = "Made By Astrokxzn",
 Callback = function()
   end    
})
Tab:AddButton({
 Name = "Copy Discord Invite",
 Callback = function()
   setclipboard("https://discord.com/invite/YraTMbPKWD")
   end    
})