-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohTable1 = {
	["4"] = {
		["fruitPosition"] = -47.36000061035156, 34.273231506347656, 81.62511444091797,
		["fruitIndex"] = 1
	},
	["3"] = {
		["fruitPosition"] = -47.35929489135742, 34.644203186035156, 89.44960021972656,
		["fruitIndex"] = 4
	},
	["2"] = {
		["fruitPosition"] = -47.35474395751953, 34.783287048339844, 83.4586410522461,
		["fruitIndex"] = 5
	}
}

game:GetService("ReplicatedStorage").Remotes.GamemodeManager.RequestFruitDrop:InvokeServer(ohTable1)