-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "AddData"
local ohString2 = "\255" --- And to stop rollback i guess just change to "VFX"

game:GetService("ReplicatedStorage").ReplicatedStorage_CLOUD.ServerSide:FireServer(ohString1, ohString2)