-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "gacha_pet",
    [2] = {
        ["1"] = 1000
    }
}

game:GetService("ReplicatedStorage").RemoteFunction:InvokeServer(unpack(args))