while true do wait()
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = {
            [1] = "Mug",
            [2] = "ShortRoundMug"
        },
        [2] = {
            [1] = "Cream",
            [2] = "WhippedCreamGreen"
        },
        [3] = {
            [1] = "Topping1",
            [2] = "CrushedCandyCane"
        },
        [4] = {
            [1] = "Topping2",
            [2] = "CandyCane"
        }
    }
}

game:GetService("ReplicatedStorage").RuntimeEvents.CocoaExit:FireServer(unpack(args))
end