-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Legendary"
}

game:GetService("Players").LocalPlayer.PlayerGui.SpinGui.LOL.Spin.Spin.Reward:FireServer(unpack(args))
--Change "Legendary" to Common, Uncommon, Or Epic for different rarity fruits
