local library = loadstring(game:HttpGet("https://pastebin.com/raw/HYcfs6KC", true))()
library.options.underlinecolor = "rainbow"
local w = library:CreateWindow('Naval Warfare')

w:Toggle('Rapid Fire (Hold E)', {flag = "toggle1"}) 
spawn(function()
while wait() do
 if w.flags.toggle1 then
if game.Players.LocalPlayer.Character:WaitForChild("Humanoid") then
local UIS = game:GetService("UserInputService")
while wait() do
if UIS:IsKeyDown(Enum.KeyCode.E) then
game:GetService("Players").LocalPlayer.Character["M1 Garand"]:Activate()
end
end
end
end
end
end)

w:Toggle('Infinite Ammo', {flag = "toggle2"}) 
spawn(function()
while wait(3) do
 if w.flags.toggle2 then
if game.Players.LocalPlayer.Character:WaitForChild("Humanoid") then
	-- This script was generated by Hydroxide

local oh_get_gc = getgc or false
local oh_is_x_closure = is_synapse_function or issentinelclosure or is_protosmasher_closure or is_sirhurt_closure or checkclosure or false
local oh_get_info = debug.getinfo or getinfo or false
local oh_set_upvalue = debug.setupvalue or setupvalue or setupval or false

if not oh_get_gc and not oh_is_x_closure and not oh_get_info and not oh_set_upvalue then
    warn("Your exploit does not support this script")
    return
end

local oh_find_function = function(name)
    for i,v in pairs(oh_get_gc()) do
        if type(v) == "function" and not oh_is_x_closure(v) then
            if oh_get_info(v).name == name then
                return v
            end
        end
    end
end

local oh_reload = oh_find_function("reload")
local oh_index = 4 -- replace this with the index of the upvalue
local oh_new_value = math.huge -- replace this with the value that you want to set the upvalue to

oh_set_upvalue(oh_reload, oh_index, oh_new_value)

-- WARNING: THIS SCRIPT MAY NOT WORK, DO NOT RELY ON THE UPVALUE SCANNER FOR 100% FUNCTIONAL SCRIPTS!
-- "scout_closure" may not find the correct function if there are multiple functions with the same name
end
end
end
end)

w:Toggle('Kill Opposite Team', {flag = "toggle3"}) 
spawn(function()
while wait(0.1) do
 if w.flags.toggle3 then
if game.Players.LocalPlayer.Character:WaitForChild("Humanoid") then
	for i,v in pairs(game.workspace:GetDescendants()) do 
if v.Name == "Humanoid" then
if v.Parent.Name.Team ~= game.Players.LocalPlayer.Team then
local A_1 = "shootRifle"
local A_2 = ""
local A_3 = 
{
	[1] = v.Parent.HumanoidRootPart
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1, A_2, A_3)
local A_1 = "shootRifle"
local A_2 = "hit"
local A_3 = 
{
	[1] = v
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1, A_2, A_3)
	end
end
end
 end
 end
 end
 end)

w:Section("Must have RPG GamePass")
w:Toggle('Shoot RPG', {flag = "toggle4"}) 
spawn(function()
while wait() do
 if w.flags.toggle4 then
local mouse = game.Players.LocalPlayer:GetMouse()
local A_2 = 
{
    [1] = mouse.Hit.p
}
game:GetService("ReplicatedStorage").Event:FireServer("fireRPG", A_2)
end
end
end)