local LP = game:GetService('Players').LocalPlayer
local GP = LP.Gamepasses
GP['Future Pack'].Value = true
GP['Grenade Launcher'].Value = true
GP['Frozen Upgrader'].Value = true
GP['Auto Collect'].Value = true
GP['Tycoon Color'].Value = true
GP['2x Cash'].Value = true
GP['Galaxy Dropper'].Value = true
GP['Speed Boost'].Value = true
GP['2x XP'].Value = true
GP.VIP.Value = true
GP['Golden Dropper'].Value = true